catalog = [
    {
    "_id": "product-1",
    "title": "t-shirts",
    "category": "tops",
    "image": "tshirt.jpg",
    "price": 35.99,
    "stock": 8,
    "minium": 1,
  },
  {
    "_id": "product-2",
    "title": "pants",
    "category": "bottoms",
    "image": "pants.jpg",
    "price": 67.99,
    "stock": 5,
    "minium": 1,
  },
  {
    "_id": "product-3",
    "title": "sweater",
    "category": "tops",
    "image": "sweater.jpg",
    "price": 74.99,
    "stock": 5,
    "minium": 1,
  },
  {
    "_id": "product-4",
    "title": "beanies",
    "category": "hats",
    "image": "beanie.jpg",
    "price": 27.99,
    "stock": 10,
    "minium": 1,
  },
  {
    "_id": "product-5",
    "title": "shoes",
    "category": "footware",
    "image": "shoes.jpg",
    "price": 119.99,
    "stock": 7,
    "minium": 1,
  },
  {
    "_id": "product-6",
    "title": "flannel",
    "category": "tops",
    "image": "flannel.jpg",
    "price": 54.99,
    "stock": 3,
    "minium": 1,
  },
  {
    "_id": "product-7",
    "title": "glasses",
    "category": "accessories",
    "image": "glasses.jpg",
    "price": 79.99,
    "stock": 3,
    "minium": 1,
  },
]